version: "3"
services:
  back:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    command: node ./index.js
    environment:
      PORT: 3000
      NODE_ENV: production
    restart: always
  front:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/etc/nginx/conf.d/
    depends_on:
      - back
    ports:
      - "80:80"
    restart: always
